name: Java CI gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19.0.1
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19.0.1'
          java-package: jdk
          architecture: x64

      - name: Run gradle and ant builds
        run: mvn -B package --file pom.xml
